### PR TITLE
Fix #285 parsing user handle in profile description

### LINKED ISSUE #285: Fix parsing user handle in user profile description
There is an issue when parsing @user handles from the user description, when the name stops with special characters (e.g. `@username.` -> the `.` is considered part of the username when it shouldn't).

### PR DESCRIPTION
**Pull request by ADcorpo**
Hello !

I changed the approach to detecting entities in user profile descriptions.

I am new to this so if I am making mistakes do not hesitate to tell me. Any way I can improve the quality of my future contributions I'll be glad to hear.

Best regards.

### CODE REVIEW

**Review by robertodoering — COMMENTED** [review]
Hey @ADcorpo,
thanks so much for the PR!

I just tested it and it works great! :)

Just two small things:
- I would prefer to have the regex in `twitter_regex.dart` instead of `common_regex.dart`.
- There are 2 hashtag symbols that we should test for: `#|＃`.
  - If you like you can add that to the regex and add to the checks in `parseEntities` with the second hashtag symbol (e.g `else if (part.startsWith('＃') { ... } `
 

Thanks again for your contribution to Harpy! ❤️

**Comment by ADcorpo** [comment]
No problem :) Hopefully I'll get Dart and Flutter experience this way !

I moved my regex to the correct file, which made me notice there are already separate regexes for mentions and hashtags. Moreover, they have tests ! Should I use those instead of the new entityRegex, or add test cases for it ?

Another thing I noticed is that despite my last 2 commits, hashtags beginning with ＃ do not become a clickable link in the user profile description. From my understanding this is because we call _findIndices in TwitterText with the following parameters:

```dart
    final List<int> indices = _findIndices(
      text,
      '#${hashtag.text}',
      indexStart,
    );
```

Before I go and modify something I shouldn't, is this expected behavior ? If it's not then I'll also update `twitter_text.dart`.

**Comment by robertodoering** [comment]
Yes, you can use the `hastagRegex` and `mentionRegex`!

You are right about them not being parsed correctly in `TwitterText`. Feel free to update the behavior in `_initializeEntities` to consider the 2 different hashtag symbols so that the entity gets parsed correctly :)

**Comment by ADcorpo** [comment]
Here is my proposed fix !

This is not very DRY however, is this up to the desired quality standards ?

I wanted to avoid making too many modifications as I am only getting started. Any feedback welcome !

**Comment by robertodoering** [comment]
Looks good!
We could modify the `_findIndices` method to make it cleaner but it's fine this way, I wouldn't change anything ;)

One nitpick, avoid using the dartdoc comments `///` inside of a method, just use `//` instead.

Feel free to hit the merge button whenever :)

**Review by robertodoering — APPROVED** [review]

**Comment by ADcorpo** [comment]
Many thanks !

I went ahead and replaced the dartdoc comments.

The merge button does not appear for me since I do not have write access, could you do it for me ?

**Comment by robertodoering** [comment]
Thank you fixing this issue! :)

If you want to work on other issues feel free to reach out to me if you have any question or just open a PR whenever you like!

**Comment by ADcorpo** [comment]
Thank you for your feedback :)

I'll stay around and watch for things I can enhance or issues I can fix as I make progress.

Best Regards.

**Pull request merged**
